feat: add validate contact form
Yinkusadel/portfolio-project pull request #10
Opened 2023-12-12 12:54 UTC by Yinkusadel

2023-12-18 18:45 UTC, moshoodabdullahi requested changes
Hi @Yinkusadel Awesome work so far
I was going through the code and I figured that you didn't use the formspree, please try using the formspree mention by @teckcipher [Form Spree](https://help.formspree.io/hc/en-us/articles/360013470814-Submit-forms-with-JavaScript-AJAX-)

2023-12-20 11:08 UTC, moshoodabdullahi submitted a review, later dismissed

2024-01-08 09:35 UTC, teckcipher requested changes
Nice job with the logic used for validation, I left some comments, you can check them out and resend for another review.

2024-01-08 09:35 UTC, teckcipher commented on js/validateinput.js
> +document.querySelector('.customer-contacts-form').addEventListener('submit', (event) => {
I believe we can use the form `name` attribute here instead of the query selector.

2024-01-08 09:35 UTC, teckcipher commented on index.html
> +              required
Do we need this `required`?

2024-01-08 09:35 UTC, teckcipher commented on js/validateinput.js
> +form.addEventListener('submit', function (event) {
Please, let's use a named function here. It makes debugging easier.

2024-01-08 09:35 UTC, teckcipher commented on js/validateinput.js
> +window.addEventListener('resize', function () {
same here

2024-01-10 06:11 UTC, teckcipher approved these changes

2024-01-10 06:46 UTC, moshoodabdullahi approved these changes

2024-01-10 06:55 UTC, merged