feat: add desktop version
Yinkusadel/portfolio-project pull request #5
Opened 2023-07-05 20:05 UTC by Yinkusadel

2023-07-10 20:39 UTC, teckcipher requested changes
Nice job @Yinkusadel  👏 👏 👏 

This is a nice design, linters passing and the page is responsive!

I left some comments, kindly address them and submit for another review.

2023-07-10 20:39 UTC, teckcipher commented on styles.css
> +  /*  styles for desktop version begins here header nav */
This media query contradicts the mobile-first approach, can this be removed from a media query? Or at least for a 'max-width' media query?

2023-07-10 20:39 UTC, teckcipher commented on styles.css
> +  }
I would move this to the normal css, then give it a display block/flex in the desktop media query.

2023-07-10 20:39 UTC, teckcipher commented on index.html
> -            d="M11.0001 15C11.0001 14.4477 11.4478 14 12.0001 14H28.0001C28.5524 14 29.0001 14.4477 29.0001 15C29.0001 15.5523 28.5524 16 28.0001 16H12.0001C11.4478 16 11.0001 15.5523 11.0001 15ZM11.
Any reason why all this is deleted? 🤔

2023-07-10 20:39 UTC, teckcipher commented on index.html
> +    </span>
Can you remove your email from the page? It might expose your email to more spam.

2023-07-10 20:39 UTC, teckcipher commented on styles.css
> +    background: url("/images/desktop-version/contact\ form-illustratoin-3-desktop.png") bottom right/150px 300px no-repeat;
Instead of escaping white spaces, why not remove the space from the file name itself? 🤔

2023-07-27 22:39 UTC, Yinkusadel commented
> Nice job @Yinkusadel 👏 👏 👏
> 
> This is a nice design, linters passing and the page is responsive!
> 
> I left some comments, kindly address them and submit for another review.

Will do

2023-07-27 22:40 UTC, Yinkusadel commented on index.html
> +    </span>
> Can you remove your email from the page? It might expose your email to more spam.

Thanks for calling my attention to this 👍

2023-07-27 22:44 UTC, Yinkusadel commented on styles.css
> +    background: url("/images/desktop-version/contact\ form-illustratoin-3-desktop.png") bottom right/150px 300px no-repeat;
That was a mistake, it's corrected now

2023-07-27 22:48 UTC, Yinkusadel commented on styles.css
> +  }
Nice idea....made the changes and it seems much better 😕

2023-07-27 22:49 UTC, Yinkusadel commented on index.html
> -            d="M11.0001 15C11.0001 14.4477 11.4478 14 12.0001 14H28.0001C28.5524 14 29.0001 14.4477 29.0001 15C29.0001 15.5523 28.5524 16 28.0001 16H12.0001C11.4478 16 11.0001 15.5523 11.0001 15ZM11.
They aren't deleted 🤫

2023-07-30 10:06 UTC, merged